jar: LiteSoftJson


resources: 
- $source$
- src|**.xml
- LICENSE

compiledependencies:
- ../LiteSoftCommonFoundation
- ../LiteSoftServerUtils

classpath:
- libs/server|**.jar

compileclasspath:
- libs/client|**.jar
